variables:
  # Default ctest model. Warning : overwritten if set in schedules variables (as we expect)
  CTEST_BUILD_MODEL: Continuous
  # Default behavior regarding cdash submission
  CDASH_SUBMIT: 0
  # Name of the docker image used to run examples.
  # Set by CI in siconos project for "triggered" examples.
  LAB_NAME: siconoslab # use siconoslab-occ to access to a full install including opencascade
  

# -- Template for examples build-test-install jobs --
# - Pull an image (possibly from siconos-tutorials registry)
#   named  IMAGE_NAME
.examples-build:
  image:
    name: $IMAGE_NAME
    entrypoint: [""]
  stage: test
  script:
    - env
    - sh ci_gitlab/build_and_run_examples.sh
  artifacts:
      paths:
        - build/
      expire_in: 3 days 
      reports:
        junit: $CI_PROJECT_DIR/build-examples/test_results.xml

# examples, on a standard (default) Siconos installation
# (based on current siconos-tutorials branch --> it assumes that a branch of the same name exists in siconos repo)
run-examples:
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/$LAB_NAME-occ-$CI_COMMIT_REF_SLUG
    CDASH_SUBMIT: 1
  extends: .examples-build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "pipeline"' # - Run when triggered from siconos project
 
# examples, with a standard (default) Siconos installation
# with version from release 4.4 (latest)
# Triggered manualy.
run-examples:release:
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/siconoslab-release-4.4
    CDASH_SUBMIT: 1
  extends: .examples-build
  when: manual


# examples, with a standard (default) Siconos installation
# with version from master (public last available version)
# Triggered manualy.
run-examples:master:
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/siconoslab-occ-master
    CDASH_SUBMIT: 1
  extends: .examples-build
  when: manual
